# Generated by Django 4.0.5 on 2022-07-30 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='materials',
            fields=[
                ('id_material', models.IntegerField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=50)),
                ('format', models.CharField(max_length=20)),
                ('done_by', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='user_login',
            fields=[
                ('email', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=500)),
                ('occupation', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='coordinator',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=12)),
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='site_ong.user_login')),
            ],
        ),
        migrations.CreateModel(
            name='volunteer',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=12)),
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='site_ong.user_login')),
            ],
        ),
    ]
