# Generated by Django 4.0.5 on 2022-08-07 14:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_ong', '0002_reviews_id_review_alter_materials_id_material_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='date_add',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
