# Generated by Django 4.0.5 on 2022-09-12 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_ong', '0003_reviews_date_add'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserLogin',
            new_name='UserCredentials',
        ),
        migrations.RenameField(
            model_name='materials',
            old_name='done_by',
            new_name='author',
        ),
    ]
